import { ArrowUpRight, BellRing, ClipboardList, MapPin, Plus, Radio, RefreshCw, Users, Waves } from 'lucide-react';
import { AppShell, ArrowLink, SectionHeading, StatusPill } from '@/components/app-shell';
import { OccupancyChart } from '@/components/charts';
import { ShelterCard } from '@/components/shelter-card';
import { alerts, cityTrend, shelters } from '@/data/shelters';

function Stat({ label, value, detail, icon: Icon, accent }: { label: string; value: string; detail: string; icon: typeof Users; accent?: string }) {
  return <div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><div className="flex items-start justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.16em] text-muted-foreground">{label}</p><p className="mt-3 font-display text-3xl font-semibold tracking-tight">{value}</p><p className="mt-1 text-xs text-muted-foreground">{detail}</p></div><span className={`grid h-9 w-9 place-items-center rounded-xl ${accent ?? 'bg-secondary text-secondary-foreground'}`}><Icon size={18} /></span></div></div>;
}

export default function Dashboard() {
  const totalCapacity = shelters.reduce((sum, shelter) => sum + shelter.maxCapacity, 0);
  const totalOccupancy = shelters.reduce((sum, shelter) => sum + shelter.currentOccupancy, 0);
  return <AppShell><div className="mx-auto max-w-[1500px] px-5 py-7 sm:px-8 lg:px-10">
    <div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><div className="mb-2 flex items-center gap-2 text-[10px] font-bold uppercase tracking-[.2em] text-secondary-foreground"><Radio size={13} /> Tuesday · 18 June 2024</div><h1 className="font-display text-3xl font-semibold tracking-tight sm:text-4xl">Good evening, Operations Desk.</h1><p className="mt-2 text-sm text-muted-foreground">Here is the network picture as of 20:42 local time.</p></div><button className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-3.5 py-2.5 text-xs font-semibold shadow-sm transition-colors hover:bg-muted" onClick={() => window.location.reload()} data-testid="button-refresh-dashboard"><RefreshCw size={14} />Refresh data</button></div>
    <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Network occupancy" value={`${Math.round((totalOccupancy / totalCapacity) * 100)}%`} detail={`${totalOccupancy.toLocaleString()} people currently sheltered`} icon={Users} /><Stat label="Open capacity" value={(totalCapacity - totalOccupancy).toLocaleString()} detail="spaces across 8 active shelters" icon={Waves} accent="bg-amber-50 text-amber-700" /><Stat label="Active alerts" value="04" detail="1 critical · 1 high priority" icon={BellRing} accent="bg-red-50 text-red-700" /><Stat label="Shelters online" value="08 / 08" detail="All sites reporting normally" icon={MapPin} accent="bg-emerald-50 text-emerald-700" /></div>
    <div className="mt-7 grid gap-5 xl:grid-cols-[1.4fr_.8fr]"><section className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6"><SectionHeading eyebrow="Network pulse" title="Occupancy trend" action={<div className="flex items-center gap-2 text-[10px] text-muted-foreground"><span className="h-2 w-2 rounded-full bg-secondary-foreground" />Today <span className="ml-2 h-2 w-2 rounded-full bg-amber-400" />Threshold 80%</div>} /><OccupancyChart data={cityTrend} /></section><section className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6"><SectionHeading eyebrow="Needs attention" title="Active alerts" action={<ArrowLink href="/alerts">View all</ArrowLink>} /><div className="space-y-1">{alerts.slice(0, 3).map((alert) => <div key={alert.id} className="group flex gap-3 rounded-xl p-3 transition-colors hover:bg-muted"><span className={`mt-1.5 h-2 w-2 shrink-0 rounded-full ${alert.severity === 'Critical' ? 'bg-red-500' : alert.severity === 'High' ? 'bg-orange-400' : 'bg-amber-400'}`} /><div className="min-w-0"><div className="flex items-start justify-between gap-2"><p className="text-sm font-semibold">{alert.title}</p><span className="shrink-0 text-[10px] text-muted-foreground">{alert.timestamp}</span></div><p className="mt-1 text-xs leading-5 text-muted-foreground">{alert.message}</p></div></div>)}</div></section></div>
    <div className="mt-9"><SectionHeading eyebrow="Live network" title="Shelter overview" action={<div className="flex gap-2"><button className="hidden items-center gap-1.5 rounded-lg border border-border px-3 py-2 text-xs font-semibold transition-colors hover:bg-muted sm:inline-flex" data-testid="button-plan-movement"><ClipboardList size={14} />Plan movement</button><ArrowLink href="/shelters">View all shelters</ArrowLink></div>} /><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4">{shelters.slice(0, 4).map((shelter) => <ShelterCard key={shelter.id} shelter={shelter} />)}</div></div>
    <div className="mt-9 grid gap-5 lg:grid-cols-2"><div className="rounded-2xl bg-primary p-6 text-primary-foreground"><div className="flex items-center justify-between"><p className="text-[10px] font-bold uppercase tracking-[.19em] text-primary-foreground/60">Recommended next action</p><span className="rounded-lg bg-primary-foreground/10 p-2"><ArrowUpRight size={17} /></span></div><h2 className="mt-5 max-w-md font-display text-2xl font-semibold leading-tight">Prioritize westbound arrivals for Oak Line Recreation Hub.</h2><p className="mt-3 max-w-md text-sm leading-6 text-primary-foreground/65">It has 407 open spaces, full services, and the lowest current network pressure. This keeps Ridgeway below its critical threshold.</p><button className="mt-6 inline-flex items-center gap-2 rounded-lg bg-accent px-4 py-2.5 text-xs font-bold text-accent-foreground transition-transform hover:-translate-y-0.5" data-testid="button-review-recommendation">Review recommendation <ArrowUpRight size={14} /></button></div><div className="rounded-2xl border border-border bg-card p-6 shadow-sm"><div className="flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-[.19em] text-secondary-foreground">Signal integrity</p><h2 className="mt-2 font-display text-2xl font-semibold">All systems reporting</h2></div><span className="grid h-10 w-10 place-items-center rounded-full bg-emerald-50 text-emerald-700"><Radio size={18} /></span></div><div className="mt-7 space-y-4"><div className="flex justify-between text-xs"><span className="text-muted-foreground">Shelter status updates</span><span className="font-semibold">08 / 08</span></div><div className="h-1.5 rounded-full bg-muted"><div className="h-full w-full rounded-full bg-emerald-500" /></div><div className="flex justify-between text-xs"><span className="text-muted-foreground">Data freshness under 5 min</span><span className="font-semibold">94.6%</span></div><div className="h-1.5 rounded-full bg-muted"><div className="h-full w-[94.6%] rounded-full bg-secondary-foreground" /></div></div></div></div>
  </div></AppShell>;
}