import { useMemo, useState } from 'react';
import { Filter, Search, SlidersHorizontal, X } from 'lucide-react';
import { AppShell, SectionHeading } from '@/components/app-shell';
import { ShelterCard } from '@/components/shelter-card';
import { shelters, type ShelterStatus } from '@/data/shelters';

export default function Shelters() {
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState<'All' | ShelterStatus>('All');
  const [servicesOnly, setServicesOnly] = useState(false);
  const filtered = useMemo(() => shelters.filter((shelter) => {
    const matchesQuery = `${shelter.name} ${shelter.location} ${shelter.district}`.toLowerCase().includes(query.toLowerCase());
    const matchesStatus = status === 'All' || shelter.status === status;
    return matchesQuery && matchesStatus && (!servicesOnly || shelter.medicalSupport && shelter.wheelchairAccessible);
  }), [query, status, servicesOnly]);
  return <AppShell><div className="mx-auto max-w-[1500px] px-5 py-7 sm:px-8 lg:px-10"><div className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 text-[10px] font-bold uppercase tracking-[.2em] text-secondary-foreground">Shelter network · 08 sites</p><h1 className="font-display text-3xl font-semibold tracking-tight sm:text-4xl">Shelter overview</h1><p className="mt-2 text-sm text-muted-foreground">Find the right receiving site for the next decision.</p></div><button onClick={() => { setQuery(''); setStatus('All'); setServicesOnly(false); }} className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-3.5 py-2.5 text-xs font-semibold shadow-sm hover:bg-muted" data-testid="button-clear-filters"><X size={14} />Clear filters</button></div>
    <div className="mb-7 rounded-2xl border border-border bg-card p-3 shadow-sm"><div className="flex flex-col gap-3 lg:flex-row lg:items-center"><label className="relative flex-1"><Search size={17} className="absolute left-3.5 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} className="h-11 w-full rounded-xl border border-input bg-background pl-10 pr-4 text-sm outline-none ring-offset-background transition-colors placeholder:text-muted-foreground focus:border-secondary-foreground focus:ring-2 focus:ring-ring/20" placeholder="Search shelters, streets, or districts..." aria-label="Search shelters" data-testid="input-search-shelters" /></label><div className="flex flex-wrap items-center gap-2"><span className="flex items-center gap-2 px-2 text-[10px] font-bold uppercase tracking-[.13em] text-muted-foreground"><SlidersHorizontal size={14} />Status</span>{(['All', 'Safe', 'Moderate', 'High', 'Critical'] as const).map((option) => <button key={option} onClick={() => setStatus(option)} className={`rounded-lg px-3 py-2 text-xs font-semibold transition-colors ${status === option ? 'bg-primary text-primary-foreground' : 'border border-border hover:bg-muted'}`} data-testid={`button-filter-${option.toLowerCase()}`}>{option}</button>)}<button onClick={() => setServicesOnly(!servicesOnly)} className={`ml-0 flex items-center gap-2 rounded-lg border px-3 py-2 text-xs font-semibold transition-colors ${servicesOnly ? 'border-secondary-foreground bg-secondary text-secondary-foreground' : 'border-border hover:bg-muted'}`} data-testid="button-filter-services"><Filter size={13} />Full services</button></div></div></div>
    <SectionHeading title={`${filtered.length} ${filtered.length === 1 ? 'shelter' : 'shelters'} in view`} action={<span className="text-xs text-muted-foreground">Updated continuously</span>} />
    {filtered.length ? <div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{filtered.map((shelter) => <ShelterCard key={shelter.id} shelter={shelter} />)}</div> : <div className="rounded-2xl border border-dashed border-border bg-card px-6 py-20 text-center"><div className="mx-auto grid h-12 w-12 place-items-center rounded-2xl bg-muted text-muted-foreground"><Search size={21} /></div><h2 className="mt-4 font-display text-lg font-semibold">No shelters match this view</h2><p className="mt-2 text-sm text-muted-foreground">Try a different search term or clear the active filters.</p><button onClick={() => { setQuery(''); setStatus('All'); setServicesOnly(false); }} className="mt-5 rounded-lg bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground" data-testid="button-reset-empty-filters">Reset filters</button></div>}
  </div></AppShell>;
}