import { useState } from 'react';
import { Accessibility, ArrowLeft, Check, Droplets, HeartPulse, MapPin, Phone, Save, Utensils, Users } from 'lucide-react';
import { Link, useParams } from 'wouter';
import { AppShell, SectionHeading, StatusPill } from '@/components/app-shell';
import { OccupancyChart } from '@/components/charts';
import { historyByShelter, shelters } from '@/data/shelters';
import { useAuth } from '@/auth/auth-context';

export default function ShelterDetail() {
  const { id } = useParams<{ id: string }>();
  const shelter = shelters.find((item) => item.id === id);
  const { user } = useAuth();
  const [liveOccupancy, setLiveOccupancy] = useState(shelter?.currentOccupancy ?? 0);
  const [resources, setResources] = useState({
    medicalSupport: shelter?.medicalSupport ?? false,
    foodAvailable: shelter?.foodAvailable ?? false,
    waterAvailable: shelter?.waterAvailable ?? false,
    wheelchairAccessible: shelter?.wheelchairAccessible ?? false,
  });
  const [saved, setSaved] = useState(false);
  if (!shelter) return <AppShell><div className="mx-auto max-w-3xl px-5 py-24 text-center"><h1 className="font-display text-2xl font-semibold">Shelter not found</h1><Link href="/shelters" className="mt-5 inline-flex rounded-lg bg-primary px-4 py-2.5 text-xs font-semibold text-primary-foreground" data-testid="link-back-shelters">Return to shelters</Link></div></AppShell>;
  const percentage = Math.round((liveOccupancy / shelter.maxCapacity) * 100);
  const history = historyByShelter[shelter.id] ?? historyByShelter['harbor-view'];
  const facility = [{ label: 'Medical support', key: 'medicalSupport' as const, active: resources.medicalSupport, icon: HeartPulse }, { label: 'Food available', key: 'foodAvailable' as const, active: resources.foodAvailable, icon: Utensils }, { label: 'Potable water', key: 'waterAvailable' as const, active: resources.waterAvailable, icon: Droplets }, { label: 'Wheelchair accessible', key: 'wheelchairAccessible' as const, active: resources.wheelchairAccessible, icon: Accessibility }];
  const isAssignedManager = user?.role === 'manager' && shelter.id === 'ridgeway';
  return <AppShell><div className="mx-auto max-w-[1280px] px-5 py-7 sm:px-8 lg:px-10"><Link href="/shelters" className="mb-7 inline-flex items-center gap-2 text-xs font-semibold text-muted-foreground transition-colors hover:text-foreground" data-testid="link-back-shelters"><ArrowLeft size={15} />All shelters</Link><div className="flex flex-wrap items-start justify-between gap-5"><div><div className="mb-2 flex items-center gap-3"><p className="text-[10px] font-bold uppercase tracking-[.2em] text-secondary-foreground">{shelter.district}</p><StatusPill status={shelter.status} /></div><h1 className="font-display text-3xl font-semibold tracking-tight sm:text-4xl">{shelter.name}</h1><p className="mt-2 flex items-center gap-1.5 text-sm text-muted-foreground"><MapPin size={15} />{shelter.location}</p></div><button className="inline-flex items-center gap-2 rounded-lg border border-border bg-card px-4 py-2.5 text-xs font-semibold shadow-sm hover:bg-muted" data-testid="button-contact-site"><Phone size={14} />Contact site lead</button></div>
     {isAssignedManager && <section className="mt-6 rounded-2xl border border-accent/40 bg-accent/[.08] p-5 shadow-sm sm:p-6"><div className="flex flex-wrap items-start justify-between gap-4"><div><p className="text-[10px] font-bold uppercase tracking-[.19em] text-accent-foreground">Manager workspace</p><h2 className="mt-2 font-display text-2xl font-semibold">Update site status</h2><p className="mt-1 text-sm text-muted-foreground">Demo controls for your assigned shelter. Changes stay local to this session.</p></div><span className="rounded-full bg-accent/20 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.12em] text-accent-foreground">Assigned site</span></div><div className="mt-6 grid gap-5 lg:grid-cols-[.7fr_1.3fr]"><label className="block"><span className="mb-2 block text-xs font-semibold">Current occupancy</span><input type="number" min={0} max={shelter.maxCapacity} value={liveOccupancy} onChange={(event) => { setLiveOccupancy(Math.min(shelter.maxCapacity, Math.max(0, Number(event.target.value)))); setSaved(false); }} className="h-12 w-full rounded-xl border border-input bg-card px-4 font-display text-xl outline-none focus:border-primary focus:ring-2 focus:ring-ring/20" data-testid="input-manager-occupancy" /><span className="mt-2 block text-xs text-muted-foreground">Maximum capacity: {shelter.maxCapacity.toLocaleString()}</span></label><div><p className="mb-2 text-xs font-semibold">Resource availability</p><div className="grid gap-2 sm:grid-cols-2">{facility.map(({ label, key, active, icon: Icon }) => <button type="button" key={key} onClick={() => { setResources((current) => ({ ...current, [key]: !current[key] })); setSaved(false); }} className={`flex items-center justify-between rounded-xl border p-3 text-left transition-colors ${active ? 'border-secondary bg-card' : 'border-border bg-muted/50'}`} aria-pressed={active} data-testid={`button-manager-${key}`}><span className="flex items-center gap-2.5 text-xs font-semibold"><Icon size={15} className={active ? 'text-secondary-foreground' : 'text-muted-foreground'} />{label}</span>{active && <Check size={15} className="text-emerald-600" />}</button>)}</div></div></div><div className="mt-5 flex items-center gap-3"><button type="button" onClick={() => setSaved(true)} className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2.5 text-xs font-bold text-primary-foreground" data-testid="button-save-manager-update"><Save size={14} />Save site update</button>{saved && <span className="text-xs font-semibold text-emerald-700">Local update saved for this demo.</span>}</div></section>}
     <div className="mt-8 grid gap-5 xl:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6"><SectionHeading eyebrow="Current load" title="Occupancy status" action={<span className="text-xs text-muted-foreground">Updated {shelter.updatedAt}</span>} /><div className="flex flex-wrap items-end justify-between gap-4"><div><span className="font-display text-5xl font-semibold tracking-[-.06em]">{liveOccupancy.toLocaleString()}</span><span className="ml-2 text-sm text-muted-foreground">of {shelter.maxCapacity.toLocaleString()} capacity</span><p className="mt-2 text-xs text-muted-foreground">{shelter.maxCapacity - liveOccupancy} remaining spaces</p></div><span className="font-display text-3xl font-semibold text-secondary-foreground">{percentage}%</span></div><div className="mt-6 h-2.5 rounded-full bg-muted"><div className={`h-full rounded-full ${percentage >= 90 ? 'bg-red-500' : percentage >= 75 ? 'bg-orange-400' : 'bg-secondary-foreground'}`} style={{ width: `${percentage}%` }} /></div><div className="mt-8"><p className="mb-3 text-[10px] font-bold uppercase tracking-[.18em] text-muted-foreground">Last 18 hours</p><OccupancyChart data={history} detail height={230} /></div></section><section className="rounded-2xl border border-border bg-card p-5 shadow-sm sm:p-6"><SectionHeading eyebrow="Site readiness" title="Facilities & access" /><div className="space-y-2">{facility.map(({ label, active, icon: Icon }) => <div key={label} className={`flex items-center justify-between rounded-xl border p-3.5 ${active ? 'border-border bg-background' : 'border-border/60 bg-muted/50 opacity-55'}`}><div className="flex items-center gap-3"><span className={`grid h-8 w-8 place-items-center rounded-lg ${active ? 'bg-secondary text-secondary-foreground' : 'bg-muted text-muted-foreground'}`}><Icon size={16} /></span><span className="text-sm font-medium">{label}</span></div>{active ? <Check size={17} className="text-emerald-600" /> : <span className="text-[10px] font-semibold uppercase tracking-wider text-muted-foreground">Unavailable</span>}</div>)}</div><div className="mt-7 border-t border-border pt-5"><p className="text-[10px] font-bold uppercase tracking-[.18em] text-muted-foreground">Site coordinates</p><div className="mt-3 flex h-24 items-center justify-center rounded-xl border border-dashed border-border bg-muted text-xs text-muted-foreground"><MapPin size={15} className="mr-2 text-secondary-foreground" />Map view available in the next release</div></div></section></div>
    <section className="mt-5 grid gap-4 sm:grid-cols-3"><div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><Users size={18} className="text-secondary-foreground" /><p className="mt-4 text-[10px] uppercase tracking-[.16em] text-muted-foreground">Current intake</p><p className="mt-1 font-display text-2xl font-semibold">+18 <span className="text-xs font-normal text-muted-foreground">/ hour</span></p></div><div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><MapPin size={18} className="text-secondary-foreground" /><p className="mt-4 text-[10px] uppercase tracking-[.16em] text-muted-foreground">Catchment</p><p className="mt-1 font-display text-2xl font-semibold">{shelter.district}</p></div><div className="rounded-2xl border border-border bg-card p-5 shadow-sm"><HeartPulse size={18} className="text-secondary-foreground" /><p className="mt-4 text-[10px] uppercase tracking-[.16em] text-muted-foreground">Last check-in</p><p className="mt-1 font-display text-2xl font-semibold">{shelter.updatedAt}</p></div></section>
  </div></AppShell>;
}