import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis, LineChart, Line } from 'recharts';
import type { TrendPoint } from '@/data/shelters';

export function OccupancyChart({ data, height = 250, detail = false }: { data: TrendPoint[]; height?: number; detail?: boolean }) {
  return <div className="w-full" style={{ height }} data-testid="chart-occupancy">
    <ResponsiveContainer width="100%" height="100%">
      {detail ? <LineChart data={data} margin={{ top: 10, right: 12, left: -22, bottom: 0 }}><CartesianGrid vertical={false} stroke="hsl(var(--border))" strokeDasharray="3 3" /><XAxis dataKey="time" axisLine={false} tickLine={false} tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 10 }} /><YAxis domain={[0, 100]} axisLine={false} tickLine={false} tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 10 }} tickFormatter={(v) => `${v}%`} /><Tooltip contentStyle={{ border: '1px solid hsl(var(--border))', borderRadius: 10, background: 'hsl(var(--card))', fontSize: 12 }} formatter={(value) => [`${value}%`, 'Occupancy']} /><Line type="monotone" dataKey="occupancy" stroke="hsl(var(--chart-1))" strokeWidth={3} dot={{ fill: 'hsl(var(--chart-1))', strokeWidth: 2, r: 3 }} activeDot={{ r: 5 }} /></LineChart> : <AreaChart data={data} margin={{ top: 8, right: 5, left: -24, bottom: 0 }}><defs><linearGradient id="occupancy-fill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="hsl(var(--chart-1))" stopOpacity={0.3} /><stop offset="100%" stopColor="hsl(var(--chart-1))" stopOpacity={0.02} /></linearGradient></defs><CartesianGrid vertical={false} stroke="hsl(var(--border))" strokeDasharray="3 3" /><XAxis dataKey="time" axisLine={false} tickLine={false} tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 10 }} /><YAxis domain={[0, 100]} axisLine={false} tickLine={false} tick={{ fill: 'hsl(var(--muted-foreground))', fontSize: 10 }} tickFormatter={(v) => `${v}%`} /><Tooltip contentStyle={{ border: '1px solid hsl(var(--border))', borderRadius: 10, background: 'hsl(var(--card))', fontSize: 12 }} formatter={(value) => [`${value}%`, 'Network occupancy']} /><Area type="monotone" dataKey="occupancy" stroke="hsl(var(--chart-1))" strokeWidth={3} fill="url(#occupancy-fill)" /></AreaChart>}
    </ResponsiveContainer>
  </div>;
}